//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.11 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.04.19 at 10:04:12 AM EDT 
//

@javax.xml.bind.annotation.XmlSchema(namespace = "http://demo.rules.openl.org/", elementFormDefault = javax.xml.bind.annotation.XmlNsForm.QUALIFIED)
package spring.exigen.auto;
