//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.11 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.04.19 at 10:04:12 AM EDT 
//


package spring.exigen.auto;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;
import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAnyAttribute;
import javax.xml.bind.annotation.XmlAnyElement;
import javax.xml.bind.annotation.XmlElementRef;
import javax.xml.bind.annotation.XmlType;
import javax.xml.namespace.QName;


/**
 * <p>Java class for SpreadsheetResult complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="SpreadsheetResult"&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="columnNames" type="{http://demo.rules.openl.org/}ArrayOfString" minOccurs="0"/&gt;
 *         &lt;element name="fieldsCoordinates" type="{http://demo.rules.openl.org/}string2PointMap" minOccurs="0"/&gt;
 *         &lt;element name="results" type="{http://cxf.apache.org/arrays}ArrayOfArrayOfAnyType" minOccurs="0"/&gt;
 *         &lt;element name="rowNames" type="{http://demo.rules.openl.org/}ArrayOfString" minOccurs="0"/&gt;
 *         &lt;any maxOccurs="unbounded" minOccurs="0"/&gt;
 *       &lt;/sequence&gt;
 *       &lt;anyAttribute/&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "SpreadsheetResult", namespace = "http://calc.rules.openl.org", propOrder = {
    "columnNames",
    "fieldsCoordinates",
    "results",
    "rowNames",
    "any"
})
public class SpreadsheetResult {

    @XmlElementRef(name = "columnNames", namespace = "http://calc.rules.openl.org", type = JAXBElement.class, required = false)
    protected JAXBElement<ArrayOfString> columnNames;
    @XmlElementRef(name = "fieldsCoordinates", namespace = "http://calc.rules.openl.org", type = JAXBElement.class, required = false)
    protected JAXBElement<String2PointMap> fieldsCoordinates;
    @XmlElementRef(name = "results", namespace = "http://calc.rules.openl.org", type = JAXBElement.class, required = false)
    protected JAXBElement<ArrayOfArrayOfAnyType> results;
    @XmlElementRef(name = "rowNames", namespace = "http://calc.rules.openl.org", type = JAXBElement.class, required = false)
    protected JAXBElement<ArrayOfString> rowNames;
    @XmlAnyElement(lax = true)
    protected List<Object> any;
    @XmlAnyAttribute
    private Map<QName, String> otherAttributes = new HashMap<QName, String>();

    /**
     * Gets the value of the columnNames property.
     * 
     * @return
     *     possible object is
     *     {@link JAXBElement }{@code <}{@link ArrayOfString }{@code >}
     *     
     */
    public JAXBElement<ArrayOfString> getColumnNames() {
        return columnNames;
    }

    /**
     * Sets the value of the columnNames property.
     * 
     * @param value
     *     allowed object is
     *     {@link JAXBElement }{@code <}{@link ArrayOfString }{@code >}
     *     
     */
    public void setColumnNames(JAXBElement<ArrayOfString> value) {
        this.columnNames = value;
    }

    /**
     * Gets the value of the fieldsCoordinates property.
     * 
     * @return
     *     possible object is
     *     {@link JAXBElement }{@code <}{@link String2PointMap }{@code >}
     *     
     */
    public JAXBElement<String2PointMap> getFieldsCoordinates() {
        return fieldsCoordinates;
    }

    /**
     * Sets the value of the fieldsCoordinates property.
     * 
     * @param value
     *     allowed object is
     *     {@link JAXBElement }{@code <}{@link String2PointMap }{@code >}
     *     
     */
    public void setFieldsCoordinates(JAXBElement<String2PointMap> value) {
        this.fieldsCoordinates = value;
    }

    /**
     * Gets the value of the results property.
     * 
     * @return
     *     possible object is
     *     {@link JAXBElement }{@code <}{@link ArrayOfArrayOfAnyType }{@code >}
     *     
     */
    public JAXBElement<ArrayOfArrayOfAnyType> getResults() {
        return results;
    }

    /**
     * Sets the value of the results property.
     * 
     * @param value
     *     allowed object is
     *     {@link JAXBElement }{@code <}{@link ArrayOfArrayOfAnyType }{@code >}
     *     
     */
    public void setResults(JAXBElement<ArrayOfArrayOfAnyType> value) {
        this.results = value;
    }

    /**
     * Gets the value of the rowNames property.
     * 
     * @return
     *     possible object is
     *     {@link JAXBElement }{@code <}{@link ArrayOfString }{@code >}
     *     
     */
    public JAXBElement<ArrayOfString> getRowNames() {
        return rowNames;
    }

    /**
     * Sets the value of the rowNames property.
     * 
     * @param value
     *     allowed object is
     *     {@link JAXBElement }{@code <}{@link ArrayOfString }{@code >}
     *     
     */
    public void setRowNames(JAXBElement<ArrayOfString> value) {
        this.rowNames = value;
    }

    /**
     * Gets the value of the any property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the any property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getAny().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link Object }
     * 
     * 
     */
    public List<Object> getAny() {
        if (any == null) {
            any = new ArrayList<Object>();
        }
        return this.any;
    }

    /**
     * Gets a map that contains attributes that aren't bound to any typed property on this class.
     * 
     * <p>
     * the map is keyed by the name of the attribute and 
     * the value is the string value of the attribute.
     * 
     * the map returned by this method is live, and you can add new attribute
     * by updating the map directly. Because of this design, there's no setter.
     * 
     * 
     * @return
     *     always non-null
     */
    public Map<QName, String> getOtherAttributes() {
        return otherAttributes;
    }

}
